#### postgres 开发环境配置 ####

spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port:3306}/${db.name}?useSSL=false
    #driver-class-name: com.mysql.jdbc.Driver      # mysql:mysql-connector-java:5
    driver-class-name: com.mysql.cj.jdbc.Driver    # mysql:mysql-connector-java:6+
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect