#### 生产环境配置 ####

spring:
  main:
    banner-mode: 'off'
  datasource:
    initialize: false
  jpa:
    show-sql: false                   # 控制是否输出 DDL、DML 语句，或者设置 logging.level.org.hibernate.SQL=DEBUG
    hibernate.ddl-auto: none          # none | create | create-drop | update | validate

logging:
  file: app.log                       # will rotate when they reach 10 MB
  level:                              # one of TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    root: WARN
    #org.springframework: WARN
    #org.springframework.jdbc: INFO
    #org.hibernate: WARN
    #org.hibernate.SQL: DEBUG          # 或者设置 spring.jpa.show-sql=true
    #org.hibernate.tool: ERROR
    #org.hibernate.tool.hbm2ddl: DEBUG
    #cn.gftaxi: INFO
    cn.gftaxi.lease.App: INFO